# -*- coding: utf-8 -*-
"""Construit le corps du rapport d'instruction (PDF ReportLab).

Usage : python3 scripts/audit_rapport.py
Sortie : scripts/audit_figs/audit_body.pdf (le corps, sans couverture ;
la couverture est fusionnee ensuite par scripts/audit_merge.py).
"""
import hashlib
import os
import sys

sys.path.insert(0, "/home/z/my-project/skills/pdf/scripts")
sys.path.insert(0, "/home/z/my-project/scripts")

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (CondPageBreak, Flowable, HRFlowable, Image,
                                KeepTogether, PageBreak, Paragraph,
                                SimpleDocTemplate, Spacer, Table, TableStyle)
from reportlab.platypus.tableofcontents import TableOfContents
from PIL import Image as PILImage

from audit_content_a import CH_1_4
from audit_content_b import CH_5_8

# ----------------------------------------------------------------- palette
# Cascade palette (auto-generated by design_engine.py palette-cascade,
# seed 20260827) — copie conforme de la sortie de palette.cascade.
PAGE_BG = colors.HexColor("#f4f4f5")
SECTION_BG = colors.HexColor("#ecedee")
CARD_BG = colors.HexColor("#e6e8e9")
TABLE_STRIPE = colors.HexColor("#ebeded")
HEADER_FILL = colors.HexColor("#3f5763")
COVER_BLOCK = colors.HexColor("#54788a")
BORDER = colors.HexColor("#b2c3cc")
ICON = colors.HexColor("#467b95")
ACCENT = colors.HexColor("#1f6c93")
ACCENT_2 = colors.HexColor("#c33e54")
TEXT_PRIMARY = colors.HexColor("#1d1f20")
TEXT_MUTED = colors.HexColor("#747a7d")

# ------------------------------------------------------------------ fonts
FONT_DIR = "/usr/share/fonts"
pdfmetrics.registerFont(TTFont("FreeSerif", f"{FONT_DIR}/truetype/freefont/FreeSerif.ttf"))
pdfmetrics.registerFont(TTFont("FreeSerif-Bold", f"{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf"))
pdfmetrics.registerFont(TTFont("FreeSerif-Italic", f"{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf"))
pdfmetrics.registerFont(TTFont("FreeSerif-BoldItalic", f"{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf"))
pdfmetrics.registerFont(TTFont("DejaVuSans", f"{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf"))
registerFontFamily("FreeSerif", normal="FreeSerif", bold="FreeSerif-Bold",
                   italic="FreeSerif-Italic", boldItalic="FreeSerif-BoldItalic")
registerFontFamily("DejaVuSans", normal="DejaVuSans", bold="DejaVuSans")

from pdf import install_font_fallback  # noqa: E402  (skill helper)
install_font_fallback()

# ------------------------------------------------------------------ layout
PAGE_W, PAGE_H = A4
MARGIN = 60
AVAIL_W = PAGE_W - 2 * MARGIN
AVAIL_H = PAGE_H - 66 - 62
MAX_KEEP = PAGE_H * 0.4

OUT = "/home/z/my-project/scripts/audit_figs/audit_body.pdf"
DOC_TITLE = "Légalement Subjective sous examen — rapport d'instruction"

# ------------------------------------------------------------------ styles
S = {}
S["body"] = ParagraphStyle("body", fontName="FreeSerif", fontSize=10.5, leading=17,
                           alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY,
                           spaceBefore=0, spaceAfter=9)
S["h1"] = ParagraphStyle("h1", fontName="FreeSerif", fontSize=21, leading=26,
                         alignment=TA_LEFT, textColor=TEXT_PRIMARY,
                         spaceBefore=16, spaceAfter=4)
S["h2"] = ParagraphStyle("h2", fontName="FreeSerif", fontSize=14.5, leading=19,
                         alignment=TA_LEFT, textColor=HEADER_FILL,
                         spaceBefore=14, spaceAfter=7)
S["h3"] = ParagraphStyle("h3", fontName="FreeSerif", fontSize=11.5, leading=15,
                         alignment=TA_LEFT, textColor=TEXT_PRIMARY,
                         spaceBefore=12, spaceAfter=6)
S["item"] = ParagraphStyle("item", fontName="FreeSerif", fontSize=10.5, leading=16.5,
                           alignment=TA_LEFT, textColor=TEXT_PRIMARY,
                           leftIndent=18, firstLineIndent=-18, spaceAfter=7)
S["quote"] = ParagraphStyle("quote", fontName="FreeSerif-Italic", fontSize=11,
                            leading=17.5, alignment=TA_LEFT, textColor=TEXT_PRIMARY,
                            spaceAfter=2)
S["quoteattr"] = ParagraphStyle("quoteattr", fontName="FreeSerif", fontSize=8.5,
                                leading=12, alignment=TA_LEFT, textColor=TEXT_MUTED,
                                spaceBefore=4)
S["stat"] = ParagraphStyle("stat", fontName="FreeSerif", fontSize=19, leading=23,
                           alignment=TA_CENTER, textColor=ACCENT)
S["statlabel"] = ParagraphStyle("statlabel", fontName="FreeSerif", fontSize=8.5,
                                leading=11.5, alignment=TA_CENTER, textColor=TEXT_MUTED)
S["caption"] = ParagraphStyle("caption", fontName="FreeSerif", fontSize=8.5,
                              leading=12, alignment=TA_CENTER, textColor=TEXT_MUTED,
                              spaceBefore=3, spaceAfter=6)
S["note"] = ParagraphStyle("note", fontName="FreeSerif", fontSize=9.2, leading=14,
                           alignment=TA_LEFT, textColor=TEXT_PRIMARY)
S["th"] = ParagraphStyle("th", fontName="FreeSerif", fontSize=9.5, leading=12.5,
                         alignment=TA_CENTER, textColor=colors.white)
S["td"] = ParagraphStyle("td", fontName="FreeSerif", fontSize=9, leading=12.5,
                         alignment=TA_LEFT, textColor=TEXT_PRIMARY)
S["toc0"] = ParagraphStyle("toc0", fontName="FreeSerif", fontSize=11, leading=20,
                           leftIndent=6, textColor=TEXT_PRIMARY)
S["toctitle"] = ParagraphStyle("toctitle", fontName="FreeSerif", fontSize=21,
                               leading=26, textColor=TEXT_PRIMARY, spaceAfter=14)


class BodyStartMarker(Flowable):
    """Marque la premiere page du corps (numerotation arabe)."""

    def __init__(self):
        super().__init__()
        self.width = 0
        self.height = 0

    def draw(self):
        pass


class TocDocTemplate(SimpleDocTemplate):
    """SimpleDocTemplate + alimentation de la TOC + debut du corps."""

    def __init__(self, *a, **kw):
        super().__init__(*a, **kw)
        self._body_start = None
        self._toc_seen = set()

    def beforeDocument(self):
        self._toc_seen = set()

    def afterFlowable(self, flowable):
        if isinstance(flowable, BodyStartMarker):
            self._body_start = self.page
            return
        if hasattr(flowable, "bookmark_name"):
            key = getattr(flowable, "bookmark_key", "")
            if key and key not in self._toc_seen:
                self._toc_seen.add(key)
                level = getattr(flowable, "bookmark_level", 0)
                text = getattr(flowable, "bookmark_text", "")
                # numero AFFICHE (arabe, reset apres le sommaire) pour la TOC
                bs = self._body_start
                shown = self.page - bs + 1 if (bs and self.page >= bs) else self.page
                self.notify("TOCEntry", (level, text, shown, key))


ROMAN = {1: "i", 2: "ii", 3: "iii", 4: "iv", 5: "v", 6: "vi", 7: "vii",
         8: "viii", 9: "ix", 10: "x"}


def draw_chrome(canvas, doc):
    canvas.saveState()
    # --- en-tete : titre + filet accent
    canvas.setFont("FreeSerif", 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 40, DOC_TITLE.upper())
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 47, PAGE_W - MARGIN, PAGE_H - 47)
    # --- pied de page : filet fin + auteur + numero
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 46, PAGE_W - MARGIN, 46)
    canvas.setFont("FreeSerif", 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, 34, "Instruction interne — établie au commit 3ec9f3b")
    body_start = getattr(doc, "_body_start", None)
    if body_start is None or doc.page < body_start:
        num = ROMAN.get(doc.page, str(doc.page))
    else:
        num = str(doc.page - body_start + 1)
    canvas.drawRightString(PAGE_W - MARGIN, 34, num)
    canvas.restoreState()


# ------------------------------------------------------------------ helpers
def safe_keep_together(elements):
    total = 0
    for el in elements:
        try:
            w, h = el.wrap(AVAIL_W, PAGE_H)
        except Exception:
            h = 40  # element non mesurable hors build (KeepTogether imbrique...)
        total += h
    if total <= MAX_KEEP:
        return [KeepTogether(elements)]
    if len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    return list(elements)


def add_heading(text, style, level=0):
    key = "h_" + hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p


BOOKMARK_ATTRS = ("bookmark_name", "bookmark_level", "bookmark_text",
                  "bookmark_key")


def h1_block(text):
    heading = add_heading(text, S["h1"], 0)
    rule = HRFlowable(width="100%", thickness=1.2, color=ACCENT,
                      spaceBefore=0, spaceAfter=10)
    kt = KeepTogether([heading, rule])
    # le bookmark vit sur le conteneur ET sur le paragraphe : selon que le
    # KeepTogether tient entier (notify conteneur) ou se scinde (notify
    # enfants), afterFlowable verra toujours les attributs.
    for attr in BOOKMARK_ATTRS:
        setattr(kt, attr, getattr(heading, attr))
    return [CondPageBreak(AVAIL_H * 0.25), kt]


def embed_image(path, max_w=AVAIL_W, max_h=300):
    img = PILImage.open(path)
    ow, oh = img.size
    ratio = min(max_w / ow if ow > max_w else 1.0,
                max_h / oh if oh > max_h else 1.0)
    return Image(path, width=ow * ratio, height=oh * ratio)


def make_table(spec):
    head, rows = spec["head"], spec["rows"]
    ratios = spec["ratios"]
    widths = [r * AVAIL_W * 0.98 for r in ratios]
    data = [[Paragraph("<b>%s</b>" % h, S["th"]) for h in head]]
    for row in rows:
        data.append([Paragraph(typo_fr(str(c)), S["td"]) for c in row])
    t = Table(data, colWidths=widths, hAlign="CENTER", repeatRows=1)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), HEADER_FILL),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("RIGHTPADDING", (0, 0), (-1, -1), 7),
        ("TOPPADDING", (0, 0), (-1, -1), 5.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5.5),
    ]
    for i in range(1, len(data)):
        if i % 2 == 0:
            style.append(("BACKGROUND", (0, i), (-1, i), TABLE_STRIPE))
    t.setStyle(TableStyle(style))
    out = [Spacer(1, 12)]
    if len(rows) <= 12:
        out += safe_keep_together([t])
    else:
        out.append(t)
    out.append(Paragraph(spec["caption"], S["caption"]))
    out.append(Spacer(1, 10))
    return out


def make_callout(stat, label):
    inner = Table(
        [[Paragraph("<b>%s</b>" % stat, S["stat"])],
         [Paragraph(typo_fr(label), S["statlabel"])]],
        colWidths=[390])
    inner.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), CARD_BG),
        ("BOX", (0, 0), (-1, -1), 1, ACCENT),
        ("TOPPADDING", (0, 0), (0, 0), 10),
        ("BOTTOMPADDING", (0, 0), (0, 0), 2),
        ("TOPPADDING", (0, 1), (0, 1), 2),
        ("BOTTOMPADDING", (0, 1), (0, 1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    return [Spacer(1, 8), KeepTogether([inner]), Spacer(1, 10)]


def make_statrow(stats):
    cell_w = (AVAIL_W - 24) / 3.0
    row_stats = []
    row_labels = []
    for big, label in stats:
        row_stats.append(Paragraph("<b>%s</b>" % big, S["stat"]))
        row_labels.append(Paragraph(typo_fr(label), S["statlabel"]))
    data = [[row_stats[0], "", row_stats[1], "", row_stats[2]],
            [row_labels[0], "", row_labels[1], "", row_labels[2]]]
    t = Table(data, colWidths=[cell_w, 12, cell_w, 12, cell_w], hAlign="CENTER")
    style = [
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]
    for col in (0, 2, 4):
        style += [
            ("BOX", (col, 0), (col, 1), 1, ACCENT),
            ("BACKGROUND", (col, 0), (col, 1), CARD_BG),
            ("TOPPADDING", (col, 0), (col, 0), 9),
            ("BOTTOMPADDING", (col, 0), (col, 0), 1),
            ("TOPPADDING", (col, 1), (col, 1), 1),
            ("BOTTOMPADDING", (col, 1), (col, 1), 9),
        ]
    t.setStyle(TableStyle(style))
    return [Spacer(1, 8), KeepTogether([t]), Spacer(1, 10)]


def make_quote(text, attribution):
    inner = [[Paragraph("« %s »" % typo_fr(text), S["quote"])],
             [Paragraph("— %s" % attribution, S["quoteattr"])]]
    t = Table(inner, colWidths=[AVAIL_W * 0.86], hAlign="CENTER")
    t.setStyle(TableStyle([
        ("LINEBEFORE", (0, 0), (0, -1), 2, ACCENT),
        ("LEFTPADDING", (0, 0), (-1, -1), 16),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (0, 0), 4),
        ("BOTTOMPADDING", (0, -1), (0, -1), 4),
    ]))
    return [Spacer(1, 8)] + safe_keep_together([t]) + [Spacer(1, 8)]


def make_note(text):
    t = Table([[Paragraph(typo_fr(text), S["note"])]], colWidths=[AVAIL_W * 0.94],
              hAlign="CENTER")
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), CARD_BG),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    return [Spacer(1, 6)] + safe_keep_together([t]) + [Spacer(1, 8)]


def typo_fr(text):
    """Typographie francaise : tiret cadratin lie par espaces inseparables
    (jamais de tiret en debut de ligne dans une phrase)."""
    return text.replace(" — ", "\u00a0— ")


def render(blocks):
    story = []
    pending_h = None  # (heading elements) a coller au premier bloc suivant
    for blk in blocks:
        kind = blk[0]
        if kind in ("h1", "h2", "h3"):
            if pending_h is not None:
                # un titre suit un titre non encore rattaché : on le verse
                # direct (sinon il est ecrase et disparait du document)
                story += pending_h
        if kind == "h1":
            pending_h = h1_block(blk[1])
            continue
        if kind == "h2":
            pending_h = [CondPageBreak(90),
                         Paragraph("<b>%s</b>" % blk[1], S["h2"])]
            continue
        if kind == "h3":
            pending_h = [CondPageBreak(70),
                         Paragraph("<b>%s</b>" % blk[1], S["h3"])]
            continue

        if kind == "p":
            el = [Paragraph(typo_fr(blk[1]), S["body"])]
        elif kind == "bullets":
            el = [Paragraph("•  " + typo_fr(it), S["item"]) for it in blk[1]]
        elif kind == "nums":
            el = [Paragraph("<b>%d.</b>  %s" % (i + 1, typo_fr(it)), S["item"])
                  for i, it in enumerate(blk[1])]
        elif kind == "quote":
            el = make_quote(blk[1], blk[2])
        elif kind == "callout":
            el = make_callout(blk[1][0], blk[1][1])
        elif kind == "statrow":
            el = make_statrow(blk[1])
        elif kind == "table":
            el = make_table(blk[1])
        elif kind == "fig":
            img = embed_image(blk[1])
            cap = Paragraph(blk[2], S["caption"])
            el = [Spacer(1, 16)] + safe_keep_together([img, cap]) + [Spacer(1, 12)]
        elif kind == "note":
            el = make_note(blk[1])
        else:
            raise ValueError("bloc inconnu: %r" % kind)

        if pending_h is not None:
            # les titres portent leur propre CondPageBreak anti-orphelin :
            # pas de re-groupement (l'imbrication de conteneurs perd les
            # bookmarks de TOC).
            story += pending_h
            story += el
            pending_h = None
        else:
            story += el
    if pending_h is not None:
        story += pending_h
    return story


# ------------------------------------------------------------------ build
def main():
    doc = TocDocTemplate(
        OUT, pagesize=A4,
        leftMargin=MARGIN, rightMargin=MARGIN, topMargin=66, bottomMargin=62,
        title=DOC_TITLE, author="Z.ai", creator="Z.ai",
        subject="Audit hostile interne du projet Légalement Subjective",
    )

    toc = TableOfContents()
    toc.levelStyles = [S["toc0"]]

    story = []
    story.append(Paragraph("<b>Sommaire</b>", S["toctitle"]))
    story.append(HRFlowable(width="100%", thickness=1.2, color=ACCENT,
                            spaceBefore=0, spaceAfter=14))
    story.append(toc)
    story.append(PageBreak())
    story.append(BodyStartMarker())
    story += render(CH_1_4)
    story += render(CH_5_8)

    doc.multiBuild(story, onFirstPage=draw_chrome, onLaterPages=draw_chrome)
    print("BODY OK:", OUT, os.path.getsize(OUT), "octets")


if __name__ == "__main__":
    main()
