// ---------- CONTENU : sections 1 a 4 ----------
const bodyChildren = [];

// ===== 1. Resume executif =====
bodyChildren.push(h1("1. Résumé exécutif"));
bodyChildren.push(body("La métaphore jMail — une interface de messagerie électronique appliquée aux données judiciaires — est définitivement écartée comme direction d'interface pour la vitrine publique d'INFINITUM. Elle avait fait ses preuves dans le projet pour lequel elle avait été conçue, où des archives de correspondances réelles prenaient vie dans un cadre familier ; mais son registre, celui de la lettre et du fil de discussion, ne dit rien du profil cognitif d'un juge, et son identité appartient à un autre projet. Le présent rapport documente la décision, la recherche en ligne qui l'accompagne, et le choix d'une nouvelle direction."));
bodyChildren.push(body("Cinq directions candidates, radicalement différentes, ont été conçues et matérialisées dans un prototype jetable consultable : L'Encyclopédie (l'entité judiciaire comme article savant), Le Dossier (la forme native de la procédure), L'Observatoire (le monde judiciaire comme ciel étoilé), L'Anatomie (la carte psycho-neurale comme planche d'atlas) et La Gazette (le quotidien de l'intelligence judiciaire). Chacune respecte les règles non négociables du projet : thème clair et sobre, esthétique juridique professionnelle, données réelles vérifiables, vitrine publique en lecture seule."));
bodyChildren.push(body("La recommandation finale procède par synthèse : adopter L'Encyclopédie comme trame maîtresse de toute la vitrine — chaque juge, avocat, juridiction, affaire ou doctrine devient un article avec notice d'autorité, notes de bas de page et renvois — et réserver aux neuf modules analytiques le traitement en planches savantes, calqué sur la structure historique de l'Encyclopédie de Diderot et d'Alembert, qui comptait onze volumes de planches gravées à côté de ses volumes de texte. La Gazette survit comme page d'accueil éditoriale, le Dossier comme format d'export d'étude. Rien ne se perd, tout se classe."));

// ===== 2. Contexte et objectifs =====
bodyChildren.push(h1("2. Contexte et objectifs de la décision"));
bodyChildren.push(h2("2.1 Pourquoi la métaphore jMail a été écartée"));
bodyChildren.push(body("Le projet jMail avait démontré une idée juste : prendre une interface que tout le monde sait déjà utiliser et y déposer des données réelles, denses et authentiques. Le résultat rendait un fond documentaire austère immédiatement navigable, sans formation ni mode d'emploi. Cette leçon de familiarité reste acquise à INFINITUM et guide l'ensemble des cinq directions étudiées ici."));
bodyChildren.push(body("L'application littérale de la forme Gmail au monde judiciaire soulève en revanche cinq objections décisives. Premièrement, le registre de la correspondance — expéditeur, destinataire, objet, fil — ne correspond à aucune structure naturelle des données du projet : un profil cognitif n'est pas un courrier, et les neuf modules d'analyse ne sont pas des pièces jointes. Deuxièmement, l'identité visuelle de la messagerie est empruntée à un autre projet ; INFINITUM doit naître avec la sienne. Troisièmement, le courriel porte une connotation de communication privée et rapide, difficilement conciliable avec la dignité d'une vitrine juridique de référence. Quatrièmement, le fil de discussion est structurellement plat : il vieillit mal face à des entités multiples (juges, avocats, juridictions, affaires, doctrines) et à des analyses de natures différentes. Cinquièmement, l'effet de surprise d'une boîte de réception judiciaire s'épuise en quelques minutes, alors qu'une vitrine publique doit soutenir la lecture répétée et l'étude."));
bodyChildren.push(h2("2.2 Ce que la vitrine publique doit garantir"));
bodyChildren.push(body("La vitrine est le panorama public d'un travail déjà accompli : elle montre des résultats précalculés, elle ne fait pas tourner le moteur. Cette définition emporte six garanties que toute direction d'interface doit satisfaire, et qui serviront de critères d'évaluation aux cinq candidats étudiés ci-après."));
bodyChildren.push(bullet("Lecture seule intégrale : aucun bouton d'exécution, aucune saisie, aucun paramétrage laissé au visiteur ; les résultats sont publiés, jamais déclenchés.", "Lecture seule. "));
bodyChildren.push(bullet("Zéro donnée simulée : seuls des faits réels et vérifiables sont affichés ; les champs que le moteur réel n'a pas encore calculés restent explicitement vides, avec mention de leur provenance future.", "Zéro simulation. "));
bodyChildren.push(bullet("Thème clair, sobre, professionnel : le registre visuel appartient au droit — papier, encre, filets, gravure — jamais au tableau de bord technologique ; le mode sombre est proscrit.", "Esthétique juridique. "));
bodyChildren.push(bullet("Extensibilité infinie : la structure d'accueil doit pouvoir intégrer toute entité ayant existé sans refonte, conformément au principe directeur du projet.", "Infini. "));
bodyChildren.push(bullet("Capacité à loger les neuf modules d'analyse sans les dénaturer ni les aplatir en vignettes interchangeables.", "Neuf modules. "));
bodyChildren.push(bullet("Provenance visible : chaque affirmation renvoie à sa source publique — biographies officielles, collections jurisprudentielles, statistiques de session.", "Provenance. "));

// ===== 3. Methode et sources =====
bodyChildren.push(h1("3. Méthode de travail et sources"));
bodyChildren.push(body("La présente direction d'interface a été établie en trois temps. D'abord, une recherche en ligne conduite le 27 août 2026 sur les interfaces existantes de l'analyse judiciaire — Lex Machina, Pre/Dicta, Harvey, Lexis+, SCOTUSblog — ainsi que sur les registres publics d'évaluation des juges (Colorado, Utah, Californie) et sur les grands systèmes visuels de référence (vocabulaire visuel du Financial Times, atlas anatomiques historiques de la National Library of Medicine, patterns d'infobox des encyclopédies). Ensuite, un brainstorming structuré a produit cinq directions candidates, chacune issue d'une métaphore native du monde du droit ou de la connaissance savante. Enfin, chaque direction a été matérialisée en maquette haute fidélité dans un prototype jetable."));
bodyChildren.push(body("Ce prototype est un fichier HTML autonome, sans dépendance externe, consultable par double-clic : il présente six vues — un sommaire de choix puis les cinq directions — commutables par une barre flottante, par les touches de direction du clavier ou par le paramètre d'URL. La même fiche témoin, la juge Sonia Sotomayor de la Cour suprême des États-Unis, est traitée par les cinq métaphores afin de comparer à données constantes. Les faits biographiques et jurisprudentiels affichés sont réels et vérifiables auprès des sources publiques de la Cour, du Caselaw Access Project et de CourtListener ; les champs analytiques — scores, prédictions, constellations — portent un marqueur distinctif et restent sans valeur, la maquette n'affichant que leur format. Ce choix traduit en pratique la règle du zéro simulacre du projet. Les captures du prototype ont été auditées visuellement ; trois défauts détectés (deux collisions d'étiquettes en carte du ciel, une marge de notes empiétant sur les pièces du dossier) ont été corrigés avant livraison."));

// ===== 4. Constat concurrentiel =====
bodyChildren.push(h1("4. Le constat concurrentiel issu de la recherche"));
bodyChildren.push(h2("4.1 Ce que font les plateformes d'analyse judiciaire"));
bodyChildren.push(body("Pre/Dicta est l'acteur le plus proche d'INFINITUM par la matière : la plateforme profile le comportement des juges fédéraux américains — affiliation politique, formation, patrimoine, parcours — à partir d'environ quinze millions d'affaires historiques et de cinquante à cent points de données par juge, et revendique une exactitude de l'ordre de quatre-vingt-cinq pour cent sur certaines prédictions de motion. Son interface reste toutefois celle d'un logiciel d'abonnement : tableaux de bord, filtres, rapports. Lex Machina, éditée par LexisNexis, délivre des analyses de juges, cours, avocats et parties avec des graphiques réputés propres ; c'est un outil de stratégie contentieuse pour cabinets, fermé au public. Harvey, enfin, appartient à une autre catégorie : assistant génératif pour la diligence, la rédaction et la recherche, sans vocation descriptive du monde judiciaire."));
bodyChildren.push(body("Côté public et gratuit, SCOTUSblog publie depuis 2002 statistiques et analyses de session de la Cour suprême, avec une rigueur de données remarquable mais une présentation de site d'information classique ; la base de données académique de l'université Washington à Saint-Louis offre plus de deux cent cinquante variables par arrêt depuis 1953, en téléchargement plutôt qu'en exploration. Plus instructifs encore sont les registres officiels d'évaluation des juges : le Colorado et l'Utah publient des évaluations de performance destinées aux électeurs, la Californie tient une base publique de décisions disciplinaires. Ces services prouvent qu'un public existe pour la connaissance publique des juges ; aucun n'offre toutefois de profil cognitif, et aucun ne soigne l'expérience de consultation."));
bodyChildren.push(h2("4.2 Le vide stratégique"));
bodyChildren.push(body("Le constat central de la recherche est un vide : aucune plateforme au monde ne publie, gratuitement et pour tous, une encyclopédie visuelle et navigable du monde judiciaire. Les acteurs commerciaux gardent leurs profils derrière des abonnements ; les acteurs publics présentent des fiches administratives sans dimension analytique ni système visuel. INFINITUM, dont le moteur produira des mesures réelles sur corpus public, serait le premier projet à occuper cet espace — à condition de se donner une identité d'interface qui ne ressemble ni à un tableau de bord SaaS, ni à un site d'information, ni à une messagerie. C'est précisément l'objet des cinq directions suivantes."));
bodyChildren.push(tableTitle("Tableau 1 — Panorama concurrentiel synthétique"));
bodyChildren.push(makeTable(
  ["Acteur", "Nature du produit", "Accès public", "Identité d'interface", "Ce qu'INFINITUM en retient"],
  [
    ["Pre/Dicta", "Prédiction et profilage comportemental des juges", "Non — abonnement", "Tableau de bord SaaS", "La profondeur des points de données par juge ; la preuve que la matière existe"],
    ["Lex Machina (LexisNexis)", "Analytique de contentieux : juges, cours, avocats, parties", "Non — abonnement", "Tableaux de bord, graphiques", "La lisibilité des statistiques de motion ; la rigueur des jeux de données"],
    ["Harvey", "Assistant génératif pour cabinets", "Non — entreprise", "Conversation, assistant", "Rien pour la vitrine : autre catégorie de produit"],
    ["SCOTUSblog", "Journalisme de données sur la Cour suprême", "Oui — gratuit", "Site d'information", "La crédibilité du public gratuit ; les statistiques par session comme source"],
    ["Registres d'évaluation (CO, UT, CA)", "Évaluations officielles et décisions disciplinaires", "Oui — officiel", "Fiches administratives", "La preuve d'un besoin public de connaître les juges ; la prudence de ton"],
    ["Base SCOTUS (Washington University)", "Jeu de données académique, 250+ variables par arrêt", "Oui — téléchargement", "Base de données brute", "La profondeur historique depuis 1953 ; l'esprit scientifique"],
  ],
  [16, 24, 14, 20, 26],
  { boldFirstCol: true }
));
bodyChildren.push(lead("Aucun de ces acteurs ne combine les trois éléments qu'INFINITUM peut réunir : des profils cognitifs calculés sur données réelles, une accessibilité publique gratuite, et une identité visuelle mémorable. Le champ est libre ; il reste à choisir la forme."));
